### ISSUE TITLE
Simple Linear Regression with Tensorflow

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/Grokking-Machine-Learning#1]
Add a simple linear regression model using Tensorflow framework.

## Steps to follow
* Comment about your interest in the issue and the dataset you want to work with
* Tell us your approach in brief
* Let the mentor respond to you and only after that get started with the issue.
* Don't forget to check the already existing model in order to know the structure.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by sahebsunny** [comment]
Sir I love to work on it. 
I would be grateful if you can assign this issue to me. 
Thank you.

**Comment by sujal111** [comment]
Please allow me too work on this issue

**Comment by Abhijit2505** [comment]
> Sir I love to work on it.
> I would be grateful if you can assign this issue to me.
> Thank you.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by Abhijit2505** [comment]
> Please allow me too work on this issue
> 
> Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
> Let's have a chat at the community tab before starting contributions.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by Abhijit2505** [comment]
> Sir I love to work on it.
> I would be grateful if you can assign this issue to me.
> Thank you.

Please get started with the issue.

**Comment by Abhijit2505** [comment]
> Please allow me too work on this issue

please get started with the issue.

**Comment by sahebsunny** [comment]
yes sir thank you

**Comment by Abhijit2505** [comment]
@Rishikeshrajrxl please get started with boston house prediction

**Comment by Rishikeshrajrxl** [comment]
> @Rishikeshrajrxl please get started with Boston house prediction

but  @Abhijit2505  you closed that issues #11 and to told me to do #1
and here already you have assigned it to two people.

**Comment by Abhijit2505** [comment]
> > @Rishikeshrajrxl please get started with Boston house prediction
> 
> but @Abhijit2505 you closed that issues #11 and to told me to do #1
> and here already you have assigned it to two people.

I believe I did not assign them the **Boston House Prediction** dataset. So please implement the model with the Boston House Prediction dataset.
