### ISSUE TITLE
Text summarization

### ISSUE THREAD

**Issue by Vashuev** [edualgo/Grokking-Machine-Learning#105]
Hello @Abhijit2505, I want to implement a text summarization model. It will output the summary by extracting the important sentences from huge articles.
I will try to make it all from scratch, except using an nltk function for removing basic words i.e the, and, a, it, will, etc.

please label and assign it to me as soon as possible.

**Comment by Abhijit2505** [comment]
@Rohit-bisht-rise please get started.
