### ISSUE TITLE
Predicting-Boston-House-Prices

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [edualgo/Grokking-Machine-Learning#11]
Boston dataset is  the one that  a Machine learner should first do. 
Here I will be predicting the prices.

**Comment by Rishikeshrajrxl** [comment]
Please assign me this issue

**Comment by Abhijit2505** [comment]
> Boston dataset is the one that a Machine learner should first do.
> Here I will be predicting the prices.

I am closing the issue and assigning you to the linear regression issue that's already opened.
