### ISSUE TITLE
Weather Analysis

### ISSUE THREAD

**Issue by Amit366** [edualgo/Grokking-Machine-Learning#112]
In this project I will take a dataset of in which I will analysis:

wind speed
variance of relative humidity
standard deviation of pressure
mean visibility
no.of times when the weather was clear
and many more

Sir please assign this issue to me.

**Comment by Abhijit2505** [comment]
Please add the related ML model too.

**Comment by Abhijit2505** [comment]
@Amit366 get started

**Comment by Amit366** [comment]
@Abhijit2505 Sir It consists of 11 analysis so can't it be level 4??

**Comment by Amit366** [comment]
And also I want to work on issue #18

**Comment by Abhijit2505** [comment]
> @Abhijit2505 Sir It consists of 11 analysis so can't it be level 4??

Contribute to learn, not to win.
