### ISSUE TITLE
Heart disease prediction using 7 ML algos

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#125]
-  PR  corresponding to issue #324 
- ML algorithms used:
1. Logistic Regression
2. Naive Bayes
3. Support Vector Machine
4. K-Nearest Neighbours
5. Decision Tree
6. Random Forest
7. XGBoost
-  Accuracy achieved: **89%**
- Dataset used: _https://www.kaggle.com/ronitf/heart-disease-uci_
- Please add DWOC Tag and level

**Comment by Abhijit2505** [comment]
@shraiyya get started.

**Comment by shraiyya** [comment]
Please close this issue!
