### ISSUE TITLE
Flight Delay prediction using scikit learn

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#127]
Dataset used: https://www.kaggle.com/usdot/flight-delays
The flight delay and cancellation data was collected and published by the DOT's Bureau of Transportation Statistics
The model can predict if the flight will get delayed or not. 5 classifiers were implemented on the dataset.
Please add the DWOC Tag and level.

**Comment by Abhijit2505** [comment]
@shraiyya get started.
