### ISSUE TITLE
Cryptocurrency Data Analysis and Visualization

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#130]
- Dataset used: coinmarketcap API
- The code contains visualizations regarding many cryptocurrencies and their market capitalization, 10 biggest gainers, and top 10 losers, Volatility in cryptocurrencies, etc.
- Please add the DWOC Tag and level.

**Comment by Abhijit2505** [comment]
@shraiyya get started.
