### ISSUE TITLE
Voice emotion prediction

### ISSUE THREAD

**Issue by Bhagyashri2000** [edualgo/Grokking-Machine-Learning#135]
Model to predict the mood of person (good/bad) according to his/her voice.
Dataset-https://www.kaggle.com/uwrfkaggler/ravdess-emotional-speech-audio

**Comment by Abhijit2505** [comment]
@Bhagyashri2000 get started but, add models one after one, for labels

**Comment by Bhagyashri2000** [comment]
Okay Sir
