### ISSUE TITLE
Cuisine Prediction using Sklearn

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#140]
- The code can predict the cuisine of a recipe, given its ingredients.
- Decision Tree is used for prediction
- Dataset used : https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DS0103EN/labs/data/recipes.csv"
- Please add DWOC tag and level

**Comment by Abhijit2505** [comment]
@shraiyya get started.
