### ISSUE TITLE
Comparing cosmetics by the ingredients used

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#142]
1. The project helps us predict which cosmetics are good for us from a large dataset of cosmetics.
2. Preprocessing the ingredient lists is done via word embedding, then visualizes ingredient similarity using the Dimensionality-Reduction technique called t-SNE, and the visualization is done using Bokeh.
3. It is a content-based recommendation system based on the chemical components of cosmetics.
4. This Project also includes the concepts of natural language processing and word embedding.
5. . Please add the DWOC Tag and Level of the Code.

**Comment by Abhijit2505** [comment]
@shraiyya get started.
