### ISSUE TITLE
Reducing Traffic Mortality in USA

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#150]
- The code aims to reduce _Traffic Mortality in the USA_ in a statistically sound way.We can develop a good strategy for reducing traffic-related deaths.

Project Description
- The data given to us was originally collected by the National Highway Traffic Safety Administration and the National Association of Insurance Commissioners. This particular dataset was compiled and released as a CSV-file by FiveThirtyEight under the CC-BY4.0 license.
- Data wrangling, plotting, dimensionality reduction, and unsupervised clustering is used. 
Data Visualisation is done with Seaborn and **Linear Regression, PCA, and Kmeans algorithms** are used.
- Tech Stack:

1. Pandas
2. Numpy
3. Scikit Learn

- Please add the **DWOC Tag and Level**.

**Comment by Abhijit2505** [comment]
@shraiyya get started. Make sure this is your last PR for DWOC because we are at the end of the two-month long program.

**Comment by shraiyya** [comment]
Yes Sure.
There are 2 more PRs actually.
Can I be assigned to two more issues at the same time?
