### ISSUE TITLE
Analyzing Uber data

### ISSUE THREAD

**Issue by Bhagyashri2000** [edualgo/Grokking-Machine-Learning#151]
Analyzing and visualizing Uber data so that future plans can be made accordingly.
dataset: https://www.kaggle.com/fivethirtyeight/uber-pickups-in-new-york-city

**Comment by Abhijit2505** [comment]
@Bhagyashri2000 get started, also make sure this is your last PR for DWOC as we have reached the end of the two-month long program.

**Comment by Bhagyashri2000** [comment]
Okay
