### ISSUE TITLE
MIND analysis and classification

### ISSUE THREAD

**Issue by infiniteoverflow** [edualgo/Grokking-Machine-Learning#153]
Dataset used : https://www.kaggle.com/arashnic/mind-news-dataset

We are planning to Detect the entity of the news content using Spacy and also use various classification algorithms to classify the text contents.

**Comment by Abhijit2505** [comment]
@infiniteoverflow get started and make sure this is your last PR for DWOC, because we are completing two months of the program.

**Comment by infiniteoverflow** [comment]
Yes , sure. This would be my last PR. Thanks a lot !!
