### ISSUE TITLE
Non-linear SVM using Tensorflow

### ISSUE THREAD

**Issue by infiniteoverflow** [edualgo/Grokking-Machine-Learning#16]
Here we implement a multi-class classifier with SVM using non-linear kernels on the IRIS Dataset.

**Comment by Abhijit2505** [comment]
@infiniteoverflow please get started.

**Comment by infiniteoverflow** [comment]
Thanks !!

**Comment by infiniteoverflow** [comment]
I have add the model. Kindly have a look at it. @Abhijit2505
