### ISSUE TITLE
Bitcoin Price Predictor

### ISSUE THREAD

**Issue by avinashkranjan** [edualgo/Grokking-Machine-Learning#163]
## AIM 
- Building a **Bitcoin Price Predictor** Using [Kaggle Historical Dataset](https://www.kaggle.com/mczielinski/bitcoin-historical-data).

## Details
-  I think It would be a great addition to the existing collection of ML notebooks.
- Creating a Google Collab Notebook.
- Generating Prediction Based on the data fed.

### Willing to work on the Issue ?

- [x] Yes
- [ ] No

**Comment by Abhijit2505** [comment]
@avinashkranjan please get started

**Comment by rijuld** [comment]
Hi @Abhijit2505 Can I work on this?

**Comment by Abhijit2505** [comment]
@rijuld Yes please get started

**Comment by rijuld** [comment]
@Abhijit2505  Thanks
