### ISSUE TITLE
EDA on the Palmer Penguins Dataset using R.

### ISSUE THREAD

**Issue by khusheekapoor** [edualgo/Grokking-Machine-Learning#179]
A clear and concise description of what the feature is.
I will perform EDA on the Palmer Penguins dataset using R.

Is your feature request related to a problem? Please describe.
It will get new learners introduced to the basic commands in R.

Describe the solution you'd like.
I will make use of basic R commands and the tidyverse and ggplot2 libraries.

Please assign this to me under HacktoberFest 2021.

**Comment by Abhijit2505** [comment]
@khusheekapoor If possible can you do the same thing in Python, as you can see, we are purely a python repository.
