### ISSUE TITLE
Fruits Classification

### ISSUE THREAD

**Issue by vryan-06** [edualgo/Grokking-Machine-Learning#184]
My aim here is to build a model using various approaches that will be able to classify the image of the fruit/ vegetable out of the 131 classes on which it will be trained.
Dataset: https://www.kaggle.com/datasets/moltean/fruits

**My approach:**
- Fork this repo.
- Create and train DL models.
- Compare the models.
- Synch the forked repo.
- And then finally create a PR.

**Comment by vryan-06** [comment]
@Abhijit2505 Kindly allow me to work on this issue as part of Hacktoberfest2022. Thank you!

**Comment by HengKevin** [comment]
Can I be assigned to this issue?
