### ISSUE TITLE
Simple Linear Regression Using Sci-kit learn

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/Grokking-Machine-Learning#2]
Add a simple linear regression model using sci-kit learn library.

## Steps to follow
Comment about your interest in the issue and the dataset you want to work with
Tell us your approach in brief
Let the mentor respond to you and only after that get started with the issue.
Don't forget to check the already existing model in order to know the structure.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by nitya123-github** [comment]
I want to work  on prediction of concrete strength  issue  by linear regression using sci-kit library and  data from UCI repository  or  i can  even work on  the issue assigned by mentor

**Comment by Abhijit2505** [comment]
@nitya123-github , if you want to participate in DWOC, fill up the participant form and once winter begins from 25th Dec we can get started with this issue.

Thanks.

**Comment by nitya123-github** [comment]
yep cool  i have registered in it

**Comment by Abhijit2505** [comment]
> yep cool i have registered in it

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by Abhijit2505** [comment]
> I want to work on prediction of concrete strength issue by linear regression using sci-kit library and data from UCI repository or i can even work on the issue assigned by mentor

please get started with it

**Comment by nitya123-github** [comment]
yeah sure i will work on it!

**Comment by nitya123-github** [comment]
can u please  label it and add it to the dwoc leaderboard

**Comment by nitya123-github** [comment]
i dont think its added into the leaderboard of dwoc  as it was not labelled so kindly add my pull request @Abhijit2505
