### ISSUE TITLE
Implementing a Naive Bayes Classifier without any external libraries like scikit learn.

### ISSUE THREAD

**Issue by Rahul555-droid** [edualgo/Grokking-Machine-Learning#20]
In this notebook/script I will be implementing Naive Bayes Classifier From Scratch in python will not be using any external library.
 The implementation  might be a bit lengthy but I could make it beginner friendly

**Comment by Rahul555-droid** [comment]
@Abhijit2505 Please assign me this issue if it could be added here. I would want it for DWOC.
Thanks :)

**Comment by Abhijit2505** [comment]
@Rahul555-droid please get started
