### ISSUE TITLE
CODE OF CONDUCT file

### ISSUE THREAD

**Issue by muthuannamalai12** [edualgo/Grokking-Machine-Learning#21]
Hi,
I found that this project repository is not having a code of conduct file in this repository, kindly assign me this issue and I would like to contribute a well-formatted code of conduct file as you know code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
Kindly assign me this issue.I love to work on this issue as a part of DWOC

**Comment by Abhijit2505** [comment]
Well, for DWOC, We are accepting only ML related contributions.
For the code of conduct file addition, you need to know about the organization and our methodology first.

Closing the issue.

**Comment by muthuannamalai12** [comment]
> Well, for DWOC, We are accepting only ML related contributions.
> For the code of conduct file addition, you need to know about the organization and our methodology first.
> 
> Closing the issue.

Ok.Thank you
