### ISSUE TITLE
Implementing Evaluation metrics with python.

### ISSUE THREAD

**Issue by Rahul555-droid** [edualgo/Grokking-Machine-Learning#22]
Will implement the following evaluation metrics with only python.

1. Classification Accuracy.
2. Confusion Matrix.
3. Mean Absolute Error.
4. Root Mean Squared Error.

**Comment by Rahul555-droid** [comment]
Assign me this issue for DWOC please :)

**Comment by Abhijit2505** [comment]
@Rahul555-droid we follow, one issue to one contributor at a time.

**Comment by sujal111** [comment]
PLease assign me this issue

**Comment by Rahul555-droid** [comment]
I actually have this one ready.
So it would take me just a couple of hours to send a PR if I could get this one.
