### ISSUE TITLE
A Study of the relations of the Brain to the Size of the Head using Machine learning algorithm.

### ISSUE THREAD

**Issue by madhurima99** [edualgo/Grokking-Machine-Learning#29]
A relation between head circumference and brain weight of humans is generally believed to exist. 
I want to approach this problem and implement machine learning algorithm to establish a relationship between brain weight and head size.

@Abhijit2505 I'm participating in DWOC. It would be really nice if you assign this issue to me. 
Thank you.

**Comment by Abhijit2505** [comment]
> A relation between head circumference and brain weight of humans is generally believed to exist.
> I want to approach this problem and implement machine learning algorithm to establish a relationship between brain weight and head size.
> 
> @Abhijit2505 I'm participating in DWOC. It would be really nice if you assign this issue to me.
> Thank you.

Well this is something new !!

Please start working on it and do get-in touch with me through my email - founder.edualgo@gmail.com for further discussion about this new model.

**Comment by madhurima99** [comment]
Thank you, Sir! 
I'll mail you about the model details once I start working on it.
