### ISSUE TITLE
Multiple Linear Regression Model using Tensorflow 

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/Grokking-Machine-Learning#3]
Add a Multiple linear regression model using Tensorflow framework.

## Steps to follow
Comment about your interest in the issue and the dataset you want to work with
Tell us your approach in brief
Let the mentor respond to you and only after that get started with the issue.
Don't forget to check the already existing model in order to know the structure.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by sujal111** [comment]
Please allow me to work on this issue

**Comment by Abhijit2505** [comment]
> Please allow me to work on this issue

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by Abhijit2505** [comment]
> Please allow me to work on this issue

I have assigned one issue to you already.

**Comment by sujal111** [comment]
Yes Sir, I have completed KNN using Tensorflow . 
So ,it will be great if you kindly allow me to work on this issue Sir

**Comment by riyasingh1004** [comment]
@Abhijit2505  Can I work on this issue?

**Comment by YeswanthKumar-J** [comment]
Hi sir, I would like to work on this issue
