### ISSUE TITLE
Decision Tree Classifier on Pima Indian Diabetes dataset

### ISSUE THREAD

**Issue by infiniteoverflow** [edualgo/Grokking-Machine-Learning#30]
I would like to contribute this model

**Comment by sujal111** [comment]
This is apparently one of the famous ML modul which essentially shows hierarchical model to combine two or more classifiers which has been trained independently, and then fused them in the next level. This is done using Decision Trees. Please allow me to work on this issue

**Comment by infiniteoverflow** [comment]
@Abhijit2505 if you feel this is a legit model for the repo , can i get this issue assigned.

**Comment by Abhijit2505** [comment]
@infiniteoverflow please get started

**Comment by ksdkamesh99** [comment]
I want to work on this issue

**Comment by infiniteoverflow** [comment]
@Abhijit2505 I have made a PR with the model which can close this issue. Kindly have a check.
