### ISSUE TITLE
Titanic-Machine-Learning-from-Disaster

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [edualgo/Grokking-Machine-Learning#34]
Using a Machine learning to create a model that predicts which passengers survived the Titanic shipwreck.
Here I will Use Titanic dataset from kaggle.

**Comment by Rishikeshrajrxl** [comment]
Assign me this issue.  Under tag DWOC

**Comment by Abhijit2505** [comment]
@Rishikeshrajrxl get started.
