### ISSUE TITLE
Wine Quality Classification

### ISSUE THREAD

**Issue by ksdkamesh99** [edualgo/Grokking-Machine-Learning#36]
Need to classify wine quality dataset using sklearn or TensorFlow library

You can find the dataset at https://archive.ics.uci.edu/ml/datasets/wine+quality

**Comment by Amit366** [comment]
@Abhijit2505  can I work on this issue??

**Comment by Amit366** [comment]
@Abhijit2505 can I work on this issue??

**Comment by Amit366** [comment]
@Abhijit2505 can I work on this issue?? And please add the relevant tags.
