### ISSUE TITLE
Handwritten Character Recognition with Neural Network

### ISSUE THREAD

**Issue by ksdkamesh99** [edualgo/Grokking-Machine-Learning#37]
Classification of handwritten character recognition using Tensorflow

Dataset can be found at https://www.kaggle.com/sachinpatel21/az-handwritten-alphabets-in-csv-format

**Comment by Abhijit2505** [comment]
@ksdkamesh99 please get started.

**Comment by vilsijain** [comment]
can you assign me i can make it good i have good level
