### ISSUE TITLE
Loan prediction problem

### ISSUE THREAD

**Issue by Bhagyashri2000** [edualgo/Grokking-Machine-Learning#43]
I would like to create a model to predict the eligibility for loan approval and deploy it with flask. Dataset is available on kaggle-https://www.kaggle.com/altruistdelhite04/loan-prediction-problem-dataset

**Comment by Abhijit2505** [comment]
Did you check if this model is already available on our code base ?

**Comment by Bhagyashri2000** [comment]
Yes Sir. This problem has been solved with KNN algorithm. I want to try other algorithms and additionally I would try to deploy it with flask.

**Comment by Abhijit2505** [comment]
@Bhagyashri2000 please get started.

**Comment by vilsijain** [comment]
Sir please can you assign me
