### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [edualgo/Grokking-Machine-Learning#45]
Hi @Abhijit2505 
I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
Kindly do assign me this issue 
( config file having a proper message)

For reference, kindly check out: https://github.com/apps/welcome

**Comment by Abhijit2505** [comment]
We are only accepting ML-based issues for some days and the bot integration work will be done by the team when required.

Thanks.
