### ISSUE TITLE
Polynomial Regression model using Sci-kit Learn

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/Grokking-Machine-Learning#5]
Add a polynomial regression model using sci-kit learn library.

## Steps to follow

- Comment about your interest in the issue and the dataset you want to work with
- Tell us your approach in brief
- Let the mentor respond to you and only after that get started with the issue.
- Don't forget to check the already existing model in order to know the structure.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by yashasvimisra2798** [comment]
I would like to work on this issue as a part of DWOC.

**Comment by yashasvimisra2798** [comment]
I want to perform salary prediction of an employee using the *position_salaries* dataset from kaggle with the help of polynomial regression. Please assign this issue to me.

**Comment by Abhijit2505** [comment]
> I want to perform salary prediction of an employee using the _position_salaries_ dataset from kaggle with the help of polynomial regression. Please assign this issue to me.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

**Comment by Vidura-Wijekoon** [comment]
I would like to work on this issue as a part of DWOC2020. I am a beginner level student and I want to learn more about the Polynomial Regression model using Sci-kit Learn by studying this issue.

**Comment by Abhijit2505** [comment]
> I would like to work on this issue as a part of DWOC2020. I am a beginner level student and I want to learn more about the Polynomial Regression model using Sci-kit Learn by studying this issue.

Please get started with the issue

**Comment by Abhijit2505** [comment]
> I want to perform salary prediction of an employee using the _position_salaries_ dataset from kaggle with the help of polynomial regression. Please assign this issue to me.

One issue at a time, already assigned one issue to you.
