### ISSUE TITLE
predicting whether a given tweet is about a real disaster or not?

### ISSUE THREAD

**Issue by Bhagyashri2000** [edualgo/Grokking-Machine-Learning#53]
Using NLP, we can analyze tweets. I would like to work on this. Dataset can be found on kaggle-https://www.kaggle.com/c/nlp-getting-started/overview

**Comment by Abhijit2505** [comment]
@Bhagyashri2000 please get started

**Comment by AnshMishra2001** [comment]
Can I work on this?
