### ISSUE TITLE
Traffic Signs Reognition Using CNN

### ISSUE THREAD

**Issue by vaishnavi-1** [edualgo/Grokking-Machine-Learning#58]
I will train the dataset from Kaggle and make a CNN model for recognizing Traffic Signs. The accuracy of the model will be greater than 99%. @Abhijit2505  Kindly add the labels in this issue and assign it to me.

**Comment by Abhijit2505** [comment]
@vaishnavi-1 please get started.

**Comment by vaishnavi-1** [comment]
@Abhijit2505 Kindly, assign this issue to me.
