### ISSUE TITLE
Recreating MNIST  handwritten digits using GAN, Tensorflow

### ISSUE THREAD

**Issue by madhurima99** [edualgo/Grokking-Machine-Learning#59]
I would like to apply Generative adversarial networks (GANs) to generate images from noise like in digits MNIST.
For the same, I will be using tf.keras.datasets module to load the MNIST dataset.

@Abhijit2505  I'm participating in **DWOC**. It would be great if you assign this issue to me. 
Thank you.

**Comment by Abhijit2505** [comment]
@madhurima99 please get started.
