### ISSUE TITLE
Ridge Regression under Regularization

### ISSUE THREAD

**Issue by sujal111** [edualgo/Grokking-Machine-Learning#6]
Ridge Regression under Regularization to handle underfitting or overfitting

**Comment by priyanka2109** [comment]
I would like to work on this. Please assign me

**Comment by yashasvimisra2798** [comment]
I want to work on this issue please assign this to me.

**Comment by Abhijit2505** [comment]
> I would like to work on this. Please assign me

please get started with the issue
