### ISSUE TITLE
Implementation of KNN from Scratch without scikitlearn

### ISSUE THREAD

**Issue by shatakshisingh24** [edualgo/Grokking-Machine-Learning#60]
Hii! Understanding ML algorithms from scratch is really significant while studying ML. I can add Implementation of KNN without using libraries, with proper comments for user to understand easily.

Kindly assign me this issue with label DWOC and Level- 4 or 5.

**Comment by shatakshisingh24** [comment]
@Abhijit2505 Please assign me this issue if it could be added here. I wish to do as a part f DWOC .Thanks !

**Comment by Abhijit2505** [comment]
@shatakshisingh24 please get started.
