### ISSUE TITLE
Fake News Detector using TfidfVectorizer

### ISSUE THREAD

**Issue by sakshikhachane** [edualgo/Grokking-Machine-Learning#65]
The fake news will be detected using TfidfVectorizer in python. 
Please assign me this issue under DWOC and add labels.

**Comment by Abhijit2505** [comment]
@sakshikhachane please get started, don't forget to add documentation on TfidfVectorizer.

**Comment by sakshikhachane** [comment]
@Abhijit2505 I am sorry for the delayed response. I will create the PR tomorrow.
