### ISSUE TITLE
Least Absolute Shrinkage and Selection Operator (LASSO) 

### ISSUE THREAD

**Issue by sujal111** [edualgo/Grokking-Machine-Learning#7]
Least Absolute Shrinkage and Selection Operator (LASSO) under Regularization

**Comment by rajiv8** [comment]
i would like to solve this issue .

**Comment by Abhijit2505** [comment]
> i would like to solve this issue .

Please get started with the issue

**Comment by rajiv8** [comment]
ok i have started working on it.
