### ISSUE TITLE
Music Genre Classification with streamlit webapp

### ISSUE THREAD

**Issue by bharath-acchu** [edualgo/Grokking-Machine-Learning#75]
Music Genre classification using Convolutional Neural Networks. Implemented in Tensorflow 2.0 using the Keras API
**Overview**
tl;dr: Compare the classic approach of extract features and use a classifier (e.g SVM) against the Deep Learning approach of using CNNs on a representation of the audio (Melspectrogram) to extract features and classify. You can see both approaches on the nbs folder in the Jupyter notebooks.
and Streamlit web app is also built as interface to classify music genre along with visualisation

**Comment by Abhijit2505** [comment]
@bharath-acchu please get started.
