### ISSUE TITLE
KNN algorithm using scikit learn

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [edualgo/Grokking-Machine-Learning#8]

**Comment by Rishikeshrajrxl** [comment]
I would like to do this, please assign me this

**Comment by rajiv8** [comment]
Can you please assign this issue to me ? I would be waiting for the Permission.

**Comment by yashasvimisra2798** [comment]
I would like to work on a recommendation system problem statement using this algorithm. Please assign this issue to me.

**Comment by Abhijit2505** [comment]
> I would like to do this, please assign me this

Please get started with the issue.
