### ISSUE TITLE
Predicting Employee turnover using Scikit Learn

### ISSUE THREAD

**Issue by shraiyya** [edualgo/Grokking-Machine-Learning#90]
Dataset used: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Employee+Churn+in+Python/HR_comma_sep.csv

Please assign me this issue and add DWOC tag.

**Comment by Abhijit2505** [comment]
@shraiyya please get started.

**Comment by shraiyya** [comment]
Can you close this issue?
The PR is merged.
